#ifndef ECHTMLBUILDER_H
#define ECHTMLBUILDER_H

#include <Arduino.h>
#include "ECGPIO.h"
#include "ECGPIOManager.h"

extern ECGPIOManager ecGPIOManager;

class ECHtmlBuilder
{
    private:
        const String htmlhead = "<html>"
        "<head>"
        "<style>"
        "body{"
            "background:#424242;"
            "font-family:'LucidaGrande','LucidaSansUnicode','LucidaSans','DejaVuSans',Verdana,'sans-serif';"
            "font-size:36px;"
            "color:white;"
        "}"
        "h1{"
        "    display:block;"
            "font-weight:bold;"
        "}"
        "	"
        ".gpio.ON {"
            "background:#00C816;"
        "}"
        "	"
        ".gpio.OFF{"
            "background:#CC0003;"
        "}"
        "	"
        ".ON:hover {"
            "background:#00DC04;"
            "cursor:pointer;"
        "}"
        "	"
        ".OFF:hover {"
            "background:#FF0105;"
            "cursor:pointer;"
        "}"
        ".gpr{"
            "display:flex;"
            "width:auto;"
        "}"
        ".gps{"
            "display:inline-block;"
            "color:black;"
        "}"
        ".gpio{"
            "background:#C4C4C4;"
            "width:150px;"
            "height:150px;"
            "margin:5px;"
            "padding-left:10px;"
            "text-align:left;"
            "border-radius:20px;"
        "}"
        ".gpt{"
            "padding-top:15px;"
            "font-size:32px;"
            "font-family:'Lucida Grande','Lucida  SansUnicode','Lucida Sans','Deja Vu Sans',Verdana,'sans-serif';"
        "}"
        ".gst{"
            "padding-top:20px;"
            "font-size:42px;"
        "}"
        ".wr {"
            "margin:10pxauto;"
            "text-align:center;"
        "}"
        "input, button {"        
            "margin-top: 10px;"
            "border: 0;"
            "background-color: #313131;"
            "font-size: 24px;"
            "text-align: center;"
            "color: white;"
            "height: 50px;"
            "width: 450px;"
            "border-radius: 50px;"
            "box-shadow: 5px 6px 2px 0px #0202021a;"
        "}"
        "textarea:focus, input:focus, button:focus"
        "{"
            "outline: none;"
        "}"
        "button:hover"
        "{"
            "cursor: pointer;"
            "color: #B5B5B5;"
        "}"
        "</style>"
        "<script>"        
            "var x, g, j, t, i;"
            "function initPage()"
            "{		"
                "g = document.getElementById('gps');"
                "x = new XMLHttpRequest();"
                "x.onreadystatechange = function()"
                "{"
                    "if (x.readyState == 4 && x.status == 200)"
                    "{"
                        "g.innerHTML = x.responseText;"
                        "updatePage();"
                    "}"
                "};"
                "x.open('GET', '/cmd?cmd=statushtml');"
                "x.send();"                
            "}"
            "function toggle(_g)"
            "{"
                "x = new XMLHttpRequest();"
                "x.open('GET', '/cmd?cmd=toggle&gpio='+_g);"
                "x.send();"
                "updatePage();"
            "}"
            "function updatePage()"
            "{"
                "if (t != null)"
                    "clearTimeout(t);"
                "x = new XMLHttpRequest();"
                "x.onreadystatechange = function()"
                "{"
                    "if (x.readyState == 4 && x.status == 200)"
                    "{"
                        "j = JSON.parse(x.responseText);"
                        "for(i in j)"
                        "{"
                            "g = document.getElementById(j[i].GPIO);"
                            "g.setAttribute('class', 'gpio '+j[i].ValueText);"
                            "g.getElementsByClassName('gst')[0].innerHTML = j[i].ValueText;"
                        "}"
                    "}"
                "};"
                "x.open('GET', '/cmd?cmd=status');"
                "x.send();"
                "t = setTimeout(updatePage, 1500);"
            "}"
            "window.onload = initPage;"
        "</script>"
        "<meta charset='utf-8'>"
        "<title>index</title>"
        "</head>"
        "<body>";
        const String body = "</body></html>";    
        const String wiFiConfigPage = "<div class=\"wr\"><h1>Welcome!</h1><form action=\"/cmd\" method=\"get\">	<input type=\"hidden\" value=\"setwificonf\" name=\"cmd\" /><input name=\"ssid\" type=\"text\" placeholder=\"SSID\" /></br>	<input name=\"password\" type=\"password\" placeholder=\"PASSWORD\" /></br>	<button type=\"submit\">Save and reboot</button></form></div>";
        const String indexPage = "<div class=\"wr\"><h1>Overview</h1><div id=\"gps\" class=\"gps\"></div>";
        String GetECGPIOHtmlForECGPIO(ECGPIO* _gpio);     

    public:
        String GetWiFiConfigPage();
        String GetIndexHtml();
        String GetECGPIOHtml();
};

#endif